title: SE 371 Blog
markdown: kramdown
theme: minima
skin: dark
author: Daniel Kogeni
description: Personal blog used to document my progress throughout SE 371.
date_format: "%b %-d, %Y"
show_excerpts: true

- jekyll-feed