title: SE 371 Blog
theme: minima
skin: dark
author: Daniel Kogeni
description: Personal blog used to document my progress throughout SE 371.
date_format: "%b %-d, %Y"
show_excerpts: true

- jekyll-feed

- name: GitHub Pages
#   uses: crazy-max/ghaction-github-pages@v3.1.0
